security:
    providers:
        laFrite:
            entity:
                class: App\Entity\User
                property: username

    encoders:
        App\Entity\User:
            algorithm: bcrypt

    firewalls:
     dev:
        pattern: ^/(_(profiler|wdt)|css|images|uploads|js)/
        security: false
     main:
        pattern: ^/
        anonymous: true
        form_login:
           login_path: login
           check_path: login
           csrf_parameter: _csrf_security_token
           csrf_token_id: a_private_string
        logout:
            path: /logout
            target: /
        provider: laFrite

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER